# Generated by Django 4.2.7 on 2023-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Inventorie',
        ),
        migrations.AlterField(
            model_name='test',
            name='Turn_around_time',
            field=models.TextField(max_length=200),
        ),
    ]
