# Generated by Django 4.2.7 on 2023-12-12 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0003_alter_report_test_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Puser',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='billing_as_patient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
